[package]
name = "xq"
version = "0.1.0"
authors = ["Steve Sosik <steve@little-fluffy.cloud>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = "2.33.3"
color-backtrace = { version = "0.4" }
color-eyre = "0.5.11"
dirs = "1.0.4"
eyre = "0.6.5"
frontmatter = "0.4.0"
glob = "0.3.0"
nom = "6.2.1"
nom_locate = "3.0.2"
rand = "0.8"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
serde_yaml = "0.8.13"
shellexpand = "1.0.0"
tempfile = "3"
termion = "1.5"
toml = "0.5.6"
tui = "0.15"
unicode-width = "0.1"
unwrap = "1.2.1"
xapian-rusty = { path = "xapian-rusty" }
yaml-rust = "0.4"
