[package]
name = "zkfm"
version = "0.1.0"
authors = ["Steve Sosik <steve@little-fluffy.cloud>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#clap = "3.0.0-beta.1"
clap = "2.32.0"
color-backtrace = { version = "0.4" }
chrono = "0.4"
frontmatter = "0.4.0"
glob = "0.3.0"
serde = "1.0.115"
serde_yaml = "0.8.13"
shellexpand = "1.0.0"
tantivy = "0.13.0"
tempfile = "3"
unwrap = "1.2.1"
yaml-rust = "0.4"
